#Install the `anvil-uplink` library

In [3]:
!pip install anvil-uplink

Collecting anvil-uplink
  Downloading anvil_uplink-0.4.2-py2.py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.1/90.1 kB 1.9 MB/s eta 0:00:00
Collecting argparse (from anvil-uplink)
  Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: future in /usr/local/lib/python3.10/dist-packages (from anvil-uplink) (0.18.3)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from anvil-uplink) (1.16.0)
Collecting ws4py (from anvil-uplink)
  Downloading ws4py-0.5.1.tar.gz (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.4/51.4 kB 5.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: ws4py
  Building wheel for ws4py (setup.py) ... done
  Created wheel for ws4py: filename=ws4py-0.5.1-py3-none-any.whl size=45228 sha256=9205d4e232d75fa5dc70824763875310f5ec72d981e0b9837e011d46efb32aed
  Stored in directory: /root/.cache/pip/wheels/2e/7c/ad/d9c746276bf024d44296340869fcb169f1e5d80fb147351a57
Successfully built ws4py
Installing collected packages: ws4py, argparse, anvil-uplink
Successfully installed anvil-uplink-0.4.2 argparse-1.4.0 ws4py-0.5.1

#Importing required libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import anvil.server

# Connecting to the Anvil server
[Link](https://efficacy-predictor.anvil.app/) to the UI

In [2]:
anvil.server.connect("server_CMHBWP6GKWLK5WS53VAA5QXF-QI6HTRAOBA7DMPO5")

Connecting to wss://anvil.works/uplink
Anvil websocket open
Connected to "Default Environment" as SERVER

# Loading the dataset

In [3]:
train_df=pd.read_csv("data.csv")
train_df

,batch,code,strength,size,start,api_code,api_batch,smcc_batch,lactose_batch,starch_batch,...,tbl_tensile,fct_tensile,tbl_yield,batch_yield,dissolution_av,dissolution_min,resodual_solvent,impurities_total,impurity_o,impurity_l
0,1,25,5.0,240000,nov.18,5,2,1,2,1,...,1.412698,1.926183,95.785,94.697,93.83,86.0,0.06,0.33,0.05,0.16
1,2,25,5.0,240000,nov.18,5,2,1,2,1,...,1.412698,1.986377,98.467,97.348,99.67,92.0,0.04,0.34,0.06,0.16
2,3,25,5.0,240000,nov.18,5,2,1,2,1,...,1.412698,2.016473,98.496,99.242,97.33,92.0,0.03,0.28,0.05,0.16
3,4,25,5.0,240000,nov.18,5,2,1,2,1,...,1.474120,1.956280,97.736,98.106,94.50,89.0,0.03,0.30,0.05,0.18
4,5,25,5.0,240000,nov.18,5,2,1,2,1,...,1.443409,1.926183,98.106,98.106,92.00,88.0,0.04,0.31,0.05,0.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,1001,17,20.0,960000,apr.21,3,254,18,22,17,...,0.901424,1.100889,98.623,98.343,91.00,85.0,0.02,0.05,0.05,0.05
985,1002,17,20.0,960000,apr.21,3,254,18,22,17,...,0.939783,1.064192,98.626,98.532,89.17,84.0,0.02,0.05,0.05,0.05
986,1003,17,20.0,960000,apr.21,3,254,18,22,17,...,0.939783,1.108944,98.157,98.343,90.83,87.0,0.02,0.05,0.05,0.05
987,1004,17,20.0,960000,apr.21,3,254,18,22,17,...,1.035679,1.225385,99.336,99.242,92.67,90.0,0.02,0.05,0.05,0.05
988,1005,17,20.0,960000,apr.21,3,254,18,22,17,...,0.978141,1.240513,99.337,99.337,88.67,81.0,0.02,0.05,0.05,0.05

# Dropping unnecessary columns

In [4]:
train_df.drop(['batch', 'api_l_impurity', 'start', 'tbl_min_thickness', 'tbl_max_thickness', 'fct_min_thickness', 'fct_max_thickness', 'tbl_min_weight', 'tbl_max_weight', 'tbl_rsd_weight', 'fct_rsd_weight', 'tbl_min_hardness', 'tbl_max_hardness', 'tbl_av_hardness', 'fct_min_hardness', 'fct_max_hardness', 'fct_av_hardness', 'tbl_max_diameter', 'fct_max_diameter', 'tbl_tensile', 'fct_tensile', 'tbl_yield', 'batch_yield', 'api_ps05.1', 'dissolution_min', 'impurity_o', 'impurity_l'], axis=1, inplace=True)

In [5]:
train_df

,code,strength,size,api_code,api_batch,smcc_batch,lactose_batch,starch_batch,api_water,api_total_impurities,...,smcc_td,smcc_bd,smcc_ps01,smcc_ps05,smcc_ps09,starch_ph,starch_water,dissolution_av,resodual_solvent,impurities_total
0,25,5.0,240000,5,2,1,2,1,1.53,0.25,...,0.45,0.33,31.156,112.141,245.499,4.4,3.012,93.83,0.06,0.33
1,25,5.0,240000,5,2,1,2,1,1.53,0.25,...,0.45,0.33,31.156,112.141,245.499,4.4,3.012,99.67,0.04,0.34
2,25,5.0,240000,5,2,1,2,1,1.53,0.25,...,0.45,0.33,31.156,112.141,245.499,4.4,3.012,97.33,0.03,0.28
3,25,5.0,240000,5,2,1,2,1,1.53,0.25,...,0.45,0.33,31.156,112.141,245.499,4.4,3.012,94.50,0.03,0.30
4,25,5.0,240000,5,2,1,2,1,1.53,0.25,...,0.45,0.33,31.156,112.141,245.499,4.4,3.012,92.00,0.04,0.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,17,20.0,960000,3,254,18,22,17,1.50,0.32,...,0.45,0.33,30.363,119.557,262.707,4.5,2.463,91.00,0.02,0.05
985,17,20.0,960000,3,254,18,22,17,1.50,0.32,...,0.45,0.33,30.363,119.557,262.707,4.5,2.463,89.17,0.02,0.05
986,17,20.0,960000,3,254,18,22,17,1.50,0.32,...,0.45,0.33,30.363,119.557,262.707,4.5,2.463,90.83,0.02,0.05
987,17,20.0,960000,3,254,18,22,17,1.50,0.32,...,0.45,0.33,30.363,119.557,262.707,4.5,2.463,92.67,0.02,0.05
988,17,20.0,960000,3,254,18,22,17,1.50,0.32,...,0.45,0.33,30.363,119.557,262.707,4.5,2.463,88.67,0.02,0.05

# Dropping rows with missing values

In [6]:
train_df = train_df.dropna()
train_df.shape

(927, 29)

# Splitting data into features and target variables

In [7]:
x = train_df.iloc[:, :train_df.columns.get_loc("starch_water")+1]
y_dissolution = train_df.iloc[:, train_df.columns.get_loc("dissolution_av"):train_df.columns.get_loc("dissolution_av")+1]
y_residual = train_df.iloc[:, train_df.columns.get_loc("resodual_solvent"):train_df.columns.get_loc("resodual_solvent")+1]
y_impurity = train_df.iloc[:, train_df.columns.get_loc("impurities_total"):train_df.columns.get_loc("impurities_total")+1]

# Splitting data into training and testing sets
(commented out since we want to train our model on the entire dataset)

In [ ]:
# from sklearn.model_selection import train_test_split
# x_train_dissolution, x_test_dissolution, y_train_dissolution, y_test_dissolution = train_test_split(x, y_dissolution, test_size=0.2)
# x_train_residual, x_test_residual, y_train_residual, y_test_residual = train_test_split(x, y_residual, test_size=0.2)
# x_train_impurity, x_test_impurity, y_train_impurity, y_test_impurity = train_test_split(x, y_impurity, test_size=0.2)

# Creating machine learning models

In [8]:
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import GradientBoostingRegressor
gbr_dissolution = GradientBoostingRegressor()
gbr_dissolution.fit(x, y_dissolution.values.ravel())
gbr_residual = GradientBoostingRegressor()
gbr_residual.fit(x, y_residual.values.ravel())
br_impurity = BaggingRegressor()
br_impurity.fit(x, y_impurity.values.ravel())

BaggingRegressor()

# Making predictions

In [10]:
# y_pred_impurity = br_impurity.predict(x_test_impurity)
# y_pred_dissolution = gbr_dissolution.predict(x_test_dissolution)
# y_pred_residual = gbr_residual.predict(x_test_residual)

# Defining callable functions for the Anvil server

In [11]:
updates = []

In [12]:
@anvil.server.callable
def predict_impurity(params):
  prediction1 = gbr_dissolution.predict([params[1:]])
  prediction2 = gbr_residual.predict([params[1:]])
  prediction3 = br_impurity.predict([params[1:]])
  if params not in updates:
    updates.append(params)
  return [prediction1[0], prediction2[0], prediction3[0]]

In [13]:
@anvil.server.callable
def upload_data(params):
  global updates
  global train_df
  global gbr_dissolution
  global gbr_residual
  global br_impurity
  for data in updates:
    if data[0] == params[0]:
      data_copy = data.copy()
      new_row = data_copy[1:] + params[1:]
      row1 = pd.Series(new_row, index=train_df.columns)
      train_df = train_df.append(row1,ignore_index=True)
      updates.remove(data)

      x = train_df.iloc[:, :train_df.columns.get_loc("starch_water")+1]
      y_dissolution = train_df.iloc[:, train_df.columns.get_loc("dissolution_av"):train_df.columns.get_loc("dissolution_av")+1]
      y_residual = train_df.iloc[:, train_df.columns.get_loc("resodual_solvent"):train_df.columns.get_loc("resodual_solvent")+1]
      y_impurity = train_df.iloc[:, train_df.columns.get_loc("impurities_total"):train_df.columns.get_loc("impurities_total")+1]

      gbr_dissolution.fit(x, y_dissolution.values.ravel())
      gbr_residual.fit(x, y_residual.values.ravel())
      br_impurity.fit(x, y_impurity.values.ravel())

      return "Success"
  return "Error"

# Calculating and displaying evaluation metrics

In [ ]:
# from sklearn.metrics import mean_squared_error
# from sklearn.metrics import r2_score
# print(r2_score(y_test_impurity, y_pred_impurity))

# Visualizing predictions

In [ ]:
# plt.scatter(y_test_impurity, y_pred_impurity)
# plt.xlabel("Actual")
# plt.ylabel("Predicted")
# plt.show()

In [ ]:
anvil.server.wait_forever()